#!/bin/bash
xrdb $HOME/.Xresources
export DISPLAY=":1"
startxfce4 &
sleep 1
sudo service dbus start
echo "while :
do
/home/stardust/.local/share/vscode/bin/code --no-sandbox --verbose --wait
sleep 2
done
" | bash
